* Table of content                                                      :TOC:
- [[#about][About]]
- [[#emacs-initialization][Emacs Initialization]]
  - [[#packages-sources][Packages Sources]]
  - [[#use-package][use-package]]
- [[#start-up][Start up]]
  - [[#better-defaults][Better defaults]]
  - [[#theme][Theme]]
  - [[#font][Font]]
  - [[#turn-off-mouse-interface][Turn off mouse interface]]
  - [[#macos-specific][MacOS specific]]
- [[#development][Development]]
  - [[#whitespace-butler][Whitespace butler]]
  - [[#git][Git]]
  - [[#haskell][Haskell]]
  - [[#python][Python]]
  - [[#rust][Rust]]
  - [[#scala][Scala]]
  - [[#lua][Lua]]
  - [[#yaml][YAML]]
  - [[#json][JSON]]
  - [[#rest-client][Rest client]]
  - [[#cmake][CMake]]
- [[#features][Features]]
  - [[#backups][Backups]]
  - [[#dashboard][Dashboard]]
  - [[#history][History]]
  - [[#hydra][Hydra]]
  - [[#org][Org]]

* About
This configuration is mainly based on configuration from: 
[[https://github.com/rememberYou/.emacs.d/][Terencio Agozzino]] (=rememberYou=).

With some parts adapted from [[https://github.com/angrybacon/dotemacs][Mathieu Marques]] (=angrybacon=) config.

* Emacs Initialization

** Packages Sources

#+begin_src emacs-lisp :tangle yes
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")))
#+end_src

** use-package

To be able to manage its configuration with =use-package= it is necessary to
first install it, if you don't already.

#+begin_src emacs-lisp :tangle yes
(unless (package-installed-p 'use-package)
(package-refresh-contents)
  (package-install 'use-package))

(use-package delight :ensure t)
(use-package use-package-ensure-system-package :ensure t)
#+end_src

* Start up
** Better defaults

For a better user experience of GNU Emacs, here are the default values I use.

#+begin_src emacs-lisp :tangle yes
(setq-default
 ad-redefinition-action 'accept                   ; Silence warnings for redefinition
 cursor-in-non-selected-windows t                 ; Hide the cursor in inactive windows
 display-time-default-load-average nil            ; Don't display load average
 fill-column 80                                   ; Set width for automatic line breaks
 help-window-select t                             ; Focus new help windows when opened
 inhibit-startup-screen t                         ; Disable start-up screen
 initial-scratch-message ""                       ; Empty the initial *scratch* buffer
 indent-tabs-mode nil                             ; Stop using tabs to indent
 kill-ring-max 128                                ; Maximum length of kill ring
 load-prefer-newer t                              ; Prefers the newest version of a file
 mark-ring-max 128                                ; Maximum length of mark ring
 scroll-conservatively most-positive-fixnum       ; Always scroll by one line
 select-enable-clipboard t                        ; Merge system's and Emacs' clipboard
 tab-width 4                                      ; Set width for tabs
 use-package-always-ensure t                      ; Avoid the :ensure keyword for each package
 vc-follow-symlinks t                             ; Always follow the symlinks
 view-read-only t)                                ; Always open read-only buffers in view-mode
(cd "~/")                                         ; Move to the user directory
(column-number-mode 1)                            ; Show the column number
(display-time-mode 1)                             ; Enable time in the mode-line
(fset 'yes-or-no-p 'y-or-n-p)                     ; Replace yes/no prompts with y/n
(global-hl-line-mode)                             ; Hightlight current line
(set-default-coding-systems 'utf-8)               ; Default to utf-8 encoding
(show-paren-mode 1)                               ; Show the parent
#+end_src

** Theme

#+begin_src emacs-lisp :tangle yes
(use-package nord-theme
  :config
  (add-to-list 'custom-theme-load-path (expand-file-name "~/.emacs.d/themes/"))
  (load-theme 'nord t))

(use-package doom-modeline
  :defer 0.1
  :config (doom-modeline-mode))
#+end_src

** Font
#+begin_src emacs-lisp :tangle yes
;; Set default font
(set-face-attribute 'default nil
                    :family "Source Code Pro"
                    :height 130
                    :weight 'normal
                    :width 'normal)
#+end_src
** Turn off mouse interface

Kill all UI graphical elements as seen as the menu bar, toolbar, scrollbar and tooltip

#+begin_src emacs-lisp :tangle yes
(when window-system
  (menu-bar-mode -1)              ; Disable the menu bar
  (scroll-bar-mode -1)            ; Disable the scroll bar
  (tool-bar-mode -1)              ; Disable the tool bar
  (tooltip-mode -1))              ; Disable the tooltips
#+end_src
** MacOS specific

General remapping and $PATH settings

#+begin_src emacs-lisp :tangle yes
(when (eq system-type 'darwin)
  (setq-default
   exec-path (append exec-path '("/usr/local/bin"))  ; Add Homebrew path
   ns-command-modifier 'meta                         ; Map Meta to the Cmd key
   ns-option-modifier 'super                         ; Map Super to the Alt key
   ns-right-option-modifier nil))                    ; Disable the right Alt key
#+end_src

Initialize environment variables.

#+begin_src emacs-lisp :tangle yes
(use-package exec-path-from-shell
  :if (memq window-system '(mac ns))
  :defer 1
  :config (exec-path-from-shell-initialize))
#+end_src

* Development
** Whitespace butler
An unobtrusive way to trim spaces from end of line
#+begin_src emacs-lisp :tangle yes
(use-package ws-butler
  :hook
  ((prog-mode . ws-butler-mode))
)
#+end_src
** Git
#+begin_src emacs-lisp :tangle yes
(use-package magit)
(use-package git-gutter
  :defer 0.3
  :delight
  :init (global-git-gutter-mode +1))
(use-package git-timemachine
  :defer 1
  :delight)
#+end_src
** Haskell

==stack== based Haskell IDE with autocomplete

#+begin_src emacs-lisp :tangle yes
(use-package intero)
(add-hook 'haskell-mode-hook 'intero-mode)
#+end_src   

** Python

Install python packages: ~pip install jedi flake8 autopep8 black yapf~

Elpy: [[https://elpy.readthedocs.io/en/latest/][documentation]]

#+BEGIN_SRC emacs-lisp :tangle yes
(use-package elpy
  :ensure t
  :defer t
  :init
  (advice-add 'python-mode :before 'elpy-enable))
#+END_SRC
** Rust

#+begin_src emacs-lisp :tangle yes
(use-package rust-mode
  :hook
  ((rust-mode . cargo-minor-mode))
  :config
  (setq-default
   rust-format-on-save t))
(use-package cargo)
#+end_src

Run ~rustfmt~ on ~C-c <tab>~ for the current buffer

#+begin_src emacs-lisp :tangle yes
(add-hook 'rust-mode-hook
          (lambda ()
            (local-set-key (kbd "C-c <tab>") #'rust-format-buffer)))
#+end_src

** Scala

Ensime sucks just use =scala-mode= for syntax highlighting and indent

#+begin_src emacs-lisp :tangle yes
(use-package scala-mode
  :delight
  :interpreter ("scala" . scala-mode))
#+end_src

** Lua

#+begin_src emacs-lisp :tangle yes
(use-package lua-mode
  :delight "Λ "
  :mode "\\.lua\\'"
  :interpreter ("lua" . lua-mode))
#+end_src

** YAML

#+begin_src emacs-lisp :tangle yes
(use-package yaml-mode
  :delight "ψ "
  :mode "\\.yml\\'"
  :interpreter ("yml" . yml-mode))
#+end_src

** JSON 

#+begin_src emacs-lisp :tangle yes
(use-package json-mode
  :delight "J "
  :mode ("\\.json\\'" "\\.geojson\\'")
  :hook (before-save . my/json-mode-before-save-hook)
  :preface
  (defun my/json-mode-before-save-hook ()
    (when (eq major-mode 'json-mode)
      (json-pretty-print-buffer)))

  (defun my/json-array-of-numbers-on-one-line (encode array)
    "Prints the arrays of numbers in one line."
    (let* ((json-encoding-pretty-print
            (and json-encoding-pretty-print
                 (not (loop for x across array always (numberp x)))))
           (json-encoding-separator (if json-encoding-pretty-print "," ", ")))
      (funcall encode array)))
  :config (advice-add 'json-encode-array :around #'my/json-array-of-numbers-on-one-line))
#+end_src

** Rest client

#+begin_src emacs-lisp :tangle yes
(use-package restclient
  :ensure t
  :mode (("\\.rest\\'" . restclient-mode)))
#+end_src

** CMake

#+begin_src emacs-lisp :tangle yes
(use-package cmake-mode
  :mode ("CMakeLists\\.txt\\'" "\\.cmake\\'"))

(use-package cmake-font-lock
  :after (cmake-mode)
  :hook (cmake-mode . cmake-font-lock-activate))
#+end_src

* Features
** Backups

Customize the noisy default towards backup files.

#+begin_src emacs-lisp :tangle yes
(use-package files
  :ensure nil
  :config
  (setq-default
   backup-by-copying t
   backup-directory-alist `(("." . ,(expand-file-name "backups/" user-emacs-directory)))
   delete-old-versions t
   version-control t))
#+end_src
** Dashboard

   Dashboard on startup

#+begin_src emacs-lisp :tangle yes
(use-package dashboard
  :init
  (add-hook 'after-init-hook 'dashboard-refresh-buffer)
  :custom (dashboard-startup-banner 'logo)
  :config (dashboard-setup-startup-hook))
#+end_src

** History

Provides the ability to have commands and their history saved so that whenever
you return to work, you can re-run things as you need them.

#+begin_src emacs-lisp :tangle yes
(use-package savehist
  :ensure nil
  :custom
  (history-delete-duplicates t)
  (history-length t)
  (savehist-additional-variables '(kill-ring search-ring regexp-search-ring))
  (savehist-save-minibuffer-history 1)
  :config (savehist-mode 1))
#+end_src

** Hydra
   
[[https://github.com/abo-abo/hydra][Hydra on github]


#+begin_src emacs-lisp :tangle yes
(use-package hydra
  :bind (("C-c m" . hydra-magit/body)
         ("C-c o" . hydra-org/body)
         ))

(use-package major-mode-hydra
  :after hydra
  :preface
  (defun with-alltheicon (icon str &optional height v-adjust)
    "Displays an icon from all-the-icon."
    (s-concat (all-the-icons-alltheicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

  (defun with-faicon (icon str &optional height v-adjust)
    "Displays an icon from Font Awesome icon."
    (s-concat (all-the-icons-faicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

  (defun with-fileicon (icon str &optional height v-adjust)
    "Displays an icon from the Atom File Icons package."
    (s-concat (all-the-icons-fileicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str))

  (defun with-octicon (icon str &optional height v-adjust)
    "Displays an icon from the GitHub Octicons."
    (s-concat (all-the-icons-octicon icon :v-adjust (or v-adjust 0) :height (or height 1)) " " str)))
#+end_src

*** Hydra / Magit

Group Magit commands.

#+begin_src emacs-lisp :tangle yes
(pretty-hydra-define hydra-magit
  (:hint nil :color teal :quit-key "q" :title (with-alltheicon "git" "Magit" 1 -0.05))
  ("Action"
   (("b" magit-blame "blame")
    ("c" magit-clone "clone")
    ("i" magit-init "init")
    ("l" magit-log-buffer-file "commit log (current file)")
    ("L" magit-log-current "commit log (project)")
    ("s" magit-status "status"))))
#+end_src

*** Hydra / Org

Group Org commands.

#+begin_src emacs-lisp :tangle yes
(pretty-hydra-define hydra-org
  (:hint nil :color teal :quit-key "q" :title (with-fileicon "org" "Org" 1 -0.05))
  ("Action"
   (("A" my/org-archive-done-tasks "archive")
    ("a" org-agenda "agenda")
    ("c" org-capture "capture")
    ("d" org-decrypt-entry "decrypt")
    ("i" org-insert-link-global "insert-link")
    ("j" my/org-jump "jump-task")
    ("k" org-cut-subtree "cut-subtree")
    ("o" org-open-at-point-global "open-link")
    ("r" org-refile "refile")
    ("s" org-store-link "store-link")
    ("t" org-show-todo-tree "todo-tree"))))
#+end_src

** Org

#+begin_src emacs-lisp :tangle yes
(use-package org
  :ensure org-plus-contrib
  :delight "Θ "
  :preface
 :hook
 ((org-mode . toc-org-enable))
 :custom
 (org-todo-keywords '((sequence "TODO(t)"
                                "NEXT(n)"
                                "WAITING(w@/!)"
                                "SOMEDAY(.)" "|" "DONE(x!)" "CANCELLED(c@)")))
 (org-log-done 'time)
 (org-default-notes-file "~/src/orgmode/refile.org")
 (org-directory "~/src/orgmode")
 (org-use-effective-time t))
#+end_src

This package will maintain a TOC at the first heading that has a :TOC: tag.

#+begin_src emacs-lisp :tangle yes
(use-package toc-org :after org)
#+end_src

#+begin_src emacs-lisp :tangle yes
(use-package org-src
  :ensure nil
  :after org
  :config
  (setq-default
   org-edit-src-content-indentation 0
   org-edit-src-persistent-message nil
   org-src-tab-acts-natively t           ; Indent code in org-babel src blocks with <TAB>
   org-src-window-setup 'current-window))
#+end_src

#+begin_src emacs-lisp :tangle yes
(use-package org-agenda
  :ensure nil
  :after org
  :custom
  (org-agenda-files '("~/src/orgmode")))
#+end_src

Org capture templates


#+begin_src emacs-lisp :tangle yes
(use-package org-capture
    :ensure nil
    :after org
    :custom
    (org-capture-templates
     (quote (("t" "todo" entry (file "~/src/orgmode/refile.org")
              "* TODO %?\n%U\n%a\n")
             ("n" "note" entry (file "~/src/orgmode/refile.org")
              "* %? :NOTE:\n%U\n%a\n")))))
#+end_src

Better colors for TODO items

#+begin_src emacs-lisp :tangle yes
(use-package org-faces
  :ensure nil
  :after org
  :custom
  (org-todo-keyword-faces
   '(("TODO" . (:foreground "orchid" :weight normal))
     ("DONE" . (:foreground "olive drab" :weight normal))
     ("CANCELLED" . (:foreground "rosy brown" :weight normal))
     ("SOMEDAY" . (:foreground "slate gray" :weight normal))
     ("WAITING" . (:foreground "coral" :weight normal))
     ("NEXT" . (:foreground "dodger blue" :weight normal)))))
#+end_src
